services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: internet_income_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - IMAP_SORTER_HOST=${IMAP_SORTER_HOST}
      - IMAP_SORTER_PORT=${IMAP_SORTER_PORT}
      - IMAP_SORTER_USER=${IMAP_SORTER_USER}
      - IMAP_SORTER_PWD=${IMAP_SORTER_PWD}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - BOT_PASSWORD=${BOT_PASSWORD}
      - SITE_TITLE=${SITE_TITLE}
      - SHOW_HEADER=${SHOW_HEADER}
      - SHOW_FOOTER=${SHOW_FOOTER}
      - SHOW_BANNERS=${SHOW_BANNERS}
    networks:
      - internet_income_network
      - router

  nginx:
    image: nginx:alpine
    container_name: internet_income_nginx
    restart: unless-stopped
    labels:
      traefik.enable: '1'
      traefik.frontend.rule: Host:mii.local
      traefik.docker.network: router
      traefik.port: 80
      traefik.protocol: http
      traefik.http.routers.mii.entrypoints: websecure
      traefik.http.routers.mii.tls: 'true'
      traefik.http.services.mii.loadbalancer.server.port: 80
      dev.orbstack.domains: mii.local,admin.mii.local
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - internet_income_network
      - router
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: internet_income_db
    restart: unless-stopped
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - dbdata:/var/lib/mysql
    networks:
      - internet_income_network

networks:
  internet_income_network:
    driver: bridge
  router:
    external: true

volumes:
  dbdata:
    driver: local 