name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: internet_income_test
          MYSQL_USER: internet_income
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl, mysql, pdo_mysql, gd, zip, xdebug
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Setup application
      run: |
        cp environments/dev/common/config/main-local.php common/config/
        cp environments/dev/common/config/params-local.php common/config/
        cp environments/dev/common/config/test-local.php common/config/
        cp environments/dev/common/config/codeception-local.php common/config/
        cp environments/dev/console/config/main-local.php console/config/
        cp environments/dev/console/config/params-local.php console/config/
        cp environments/dev/console/config/test-local.php console/config/
        cp environments/dev/backend/config/test-local.php backend/config/

    - name: Run database migrations
      run: php yii_test migrate --interactive=0

    - name: Run tests with coverage
      run: vendor/bin/codecept run unit --coverage --coverage-html --coverage-xml -c common

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./common/tests/_output/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true 